### ISSUE TITLE
[Feature]: Change the Logo of Extension

### ISSUE THREAD

**Issue by savi-1311** [savi-1311/Slazy#10]
### Is your feature request related to an issue? Please describe.

Please change the logo.png. Currently, it is very detailed and not compatible with dark mode.

### Describe the solution you'd like

A logo can be less detailed and something which explains the Extension.

**Comment by arushi2715** [comment]
@savi-1311 I have changed the logo and pushed it to the master branch. You can check it out and tell me if it needs any modification.

**Comment by savi-1311** [comment]
It looks good! Closing the issue :)
